import { APP_CONFIG, GAME_CONFIG } from "./app-config";

export const SERVER_CONSTANTS = {
  port: APP_CONFIG.port,
  tickMs: GAME_CONFIG.tickMs,
  maxPlayers: GAME_CONFIG.maxPlayers,
  inputTimeoutMs: GAME_CONFIG.inputTimeoutMs,
  reconnectGraceMs: GAME_CONFIG.reconnectGraceMs,
  worldWidth: GAME_CONFIG.worldWidth,
  worldHeight: GAME_CONFIG.worldHeight,
  playerRadius: GAME_CONFIG.playerRadius,
  movePerFrame: GAME_CONFIG.movePerFrame,
  bulletSpeed: GAME_CONFIG.bulletSpeed,
  bulletTtl: GAME_CONFIG.bulletTtl,
  damage: GAME_CONFIG.damage,
  knifeMeleeDamage: GAME_CONFIG.knifeMeleeDamage,
  maxHp: GAME_CONFIG.maxHp,
  respawnFrames: GAME_CONFIG.respawnFrames,
  weaponSlotSize: GAME_CONFIG.weaponSlotSize,
  itemSlotSize: GAME_CONFIG.itemSlotSize,
  inventorySize: GAME_CONFIG.inventorySize,
  pickupRadius: GAME_CONFIG.pickupRadius,
  maxDrops: GAME_CONFIG.maxDrops,
  dropIntervalFrames: GAME_CONFIG.dropIntervalFrames,
  dropJitterFrames: GAME_CONFIG.dropJitterFrames,
  dropBatchBase: GAME_CONFIG.dropBatchBase,
  dropBatchCycle: GAME_CONFIG.dropBatchCycle,
  dropSpawnAttempts: GAME_CONFIG.dropSpawnAttempts,
  dropRandomSaltMod: GAME_CONFIG.dropRandomSaltMod,
  magSmg9mm: GAME_CONFIG.magSmg9mm,
  magAr762: GAME_CONFIG.magAr762,
  magAk762: GAME_CONFIG.magAk762,
  magSniper762: GAME_CONFIG.magSniper762,
  magM9: GAME_CONFIG.magM9,
  smgFireCooldownFrames: GAME_CONFIG.smgFireCooldownFrames,
  arFireCooldownFrames: GAME_CONFIG.arFireCooldownFrames,
  reloadDurationFrames: GAME_CONFIG.reloadDurationFrames,
  bulletSpawnOffset: GAME_CONFIG.bulletSpawnOffset,
  dropThrowOffset: GAME_CONFIG.dropThrowOffset,
  bulletHitRadiusPadding: GAME_CONFIG.bulletHitRadiusPadding,
  explosionFxFrames: GAME_CONFIG.explosionFxFrames,
  defaultGunCooldownFrames: GAME_CONFIG.defaultGunCooldownFrames,
  knifeArcHalfRad: GAME_CONFIG.knifeArcHalfRad,
  knifeMeleeRange: GAME_CONFIG.knifeMeleeRange,
  knifeCooldownFrames: GAME_CONFIG.knifeCooldownFrames,
  knifeArcFxFrames: GAME_CONFIG.knifeArcFxFrames
};
